apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo222
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/codefresh-contrib/gitops-certification-examples.git
    targetRevision: HEAD
    path: ./declarative/manifests
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: admin

  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: false
  
